sudo: false
language: node_js
node_js:
  - 'node'
cache:
  npm: false
script:
  - npm test -- --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
service_name: travis-pro
repo_token: ZwHP3zvpliJ86rEobFD8cu93fYw2moIrx
